theme: jekyll-theme-minimal
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: JosÃ© CaÃ±ete's CV
my_urls:
  email: mailto:jose.canete@ug.uchile.cl
  website: https://josecannete.github.io
  linkedin: https://josecannete.github.io
  google-scholar: https://josecannete.github.io
  github: https://josecannete.github.io
  twitter: https://josecannete.github.io
  mastodon: https://josecannete.github.io
