theme: jekyll-theme-minimal
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: JosÃ© CaÃ±ete's CV
my_urls:
  email: mailto:jose.canete@ug.uchile.cl
  website: https://josecannete.github.io
  linkedin: https://www.linkedin.com/in/jose-canete-lopez/
  google-scholar: https://scholar.google.com/citations?user=2ymtl2YAAAAJ&hl=es&oi=ao
  github: https://github.com/josecannete
  twitter: https://twitter.com/jocannete
  mastodon: https://josecannete.github.io
last_update: Dec. 2023
